# This is a reference script - it should be saved as 'appveyor.yml' in repo root.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Please fill 'version' property with a version string you want appended with `.{build}`  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

version: '0.0.0.{build}'
image: Visual Studio 2017
environment:
  github_auth_token: # this is BSData-bot encrypted OAuth token
    secure: O02JLN8Q1/zGJDgSkd2GmYNN6qO3hMspj3N6F8db7Fkx+/EQxjJ9tjJdJs6OpwAp
install:
  - ps: |
      $install_script_url = 'https://raw.githubusercontent.com/BSData/catalogue-development/master/scripts/appveyor-ci-install-script-v1.0.ps1'
      (New-Object System.Net.WebClient).DownloadString($install_script_url) | iex
build_script:
  - ps: |
      $build_script_url = 'https://raw.githubusercontent.com/BSData/catalogue-development/master/scripts/appveyor-ci-build-script-v1.0.ps1'
      (New-Object System.Net.WebClient).DownloadString($build_script_url) | iex
test_script:
  - ps: |
      $test_script_url = 'https://raw.githubusercontent.com/BSData/catalogue-development/master/scripts/appveyor-ci-test-script-v1.0.ps1'
      (New-Object System.Net.WebClient).DownloadString($test_script_url) | iex
deploy_script:
  - ps: |
      $deploy_script_url = 'https://raw.githubusercontent.com/BSData/catalogue-development/master/scripts/appveyor-ci-deploy-script-v1.0.ps1'
      (New-Object System.Net.WebClient).DownloadString($deploy_script_url) | iex
artifacts:
  - path: 'artifacts\*.bsi'
  - path: 'artifacts\*.bsr'

# delete '#' to uncomment if your repository has Gitter chat

#notifications:
#  - provider: Webhook
#    url: https://webhooks.gitter.im/e/aaaaaaaaaaaaaaaaaa   # here paste your Gitter chatroom Webhook url :)
#    on_build_success: true
#    on_build_failure: true
