name: ChatOps
on:
  issue_comment:
    types: [created]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: /command dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.SLASH_COMMAND_DISPATCH_TOKEN }}
          reaction-token: ${{ github.token }}
          config: >
            [
              {
                "command": "approve",
                "permission": "admin"
              },
              {
                "command": "preview",
                "permission": "read"
              }
            ]
